193 add notebooks to docs
scikit-activeml/scikit-activeml pull request #199
Opened 2021-11-18 16:27 UTC by tpham93

Fixes #193 and #194

2021-11-19 10:16 UTC, dakot requested changes
remove binaries and exp results

2021-11-22 10:35 UTC, mherde requested changes

2021-11-22 10:35 UTC, mherde commented on skactiveml/utils/_visualisation.py
> +                bound_must_be_given=False):
@LukasLuehrs `check_bound` should be part of the validation file.

2021-11-22 10:35 UTC, mherde commented on skactiveml/utils/_visualisation.py
> +import warnings
@LukasLuehrs Move helper functions (except for the check_bound) to the visualization package. Possible filename: `skactiveml.visualization._auxiliary_functions.py`.

2021-11-22 10:35 UTC, mherde commented on skactiveml/utils/tests/test_visualisation.py
> +import unittest
@LukasLuehrs Adjust test according to changes proposed in `skactiveml.utils._visualisation.py`.

2021-11-22 16:41 UTC, dakot approved these changes

2021-11-22 16:42 UTC, dakot requested changes
What about the changes mentioned by mherde?

2021-11-22 16:44 UTC, dakot approved these changes

2021-11-22 16:49 UTC, tpham93 commented on README.rst
> +            y[query_idx] = y_true[query_idx]
removed those spaces and changed the indentation to 4 spaces per indentation

2021-11-22 16:50 UTC, tpham93 commented on README.rst
> +    # LogisticRegression needs ititial training data otherwise a warning will
changed "ititial" to initial

2021-11-22 20:10 UTC, mherde requested changes

2021-11-22 20:10 UTC, mherde commented on skactiveml/visualization/_feature_space.py
> +from skactiveml.visualization._auxiliary_functions import mesh, check_bound, _get_boundary_args, \
relative import should be used, i.e., `..visualization._auxiliary_functions import ...`

2021-11-22 20:10 UTC, mherde commented on skactiveml/visualization/multi/_multi_annot_feature_space.py
> +from skactiveml.visualization._auxiliary_functions import mesh, check_bound, _get_contour_args, \
relative import should be used, i.e., ..visualization._auxiliary_functions import ...

2021-11-22 20:10 UTC, mherde commented on tutorials/multiple_annotators_getting_started.ipynb
> +    "# Pool-based Active Learning With Multi-annotators - Getting Started"
Multi-annotator Pool-based Active Learning - Getting Started

2021-11-22 20:11 UTC, mherde commented on tutorials/multiple_annotators_getting_started.ipynb
> +    "# Pool-based Active Learning With Multi-annotators - Getting Started"
Alternatively: Pool-based Active Learning with Multiple Annotators

2021-11-23 16:51 UTC, mherde approved these changes

2021-11-23 17:01 UTC, merged