Regression
scikit-activeml/scikit-activeml pull request #244
Opened 2022-05-31 10:33 UTC by LukasLuehrs

2022-06-02 09:46 UTC, acalma commented on docs/examples/pool/template.py
> +# _bp_add_imports
remove or add comment explaining why this is still needed

2022-06-02 09:56 UTC, acalma commented on skactiveml/base.py
> +    Bass class for scikit-activeml regressors.
Typo 

```suggestion
    Base class for scikit-activeml regressors.
```

2022-06-02 11:20 UTC, acalma commented on skactiveml/base.py
> +        entropy : numpy..ndarray, optional
```suggestion
        entropy : numpy.ndarray, optional
```

2022-06-02 12:00 UTC, acalma commented on skactiveml/pool/regression/_expected_model_change.py
> +    feature_map: callable
this is also optional, isn't it?

```suggestion
    feature_map: callable, optional
```

2022-06-02 12:00 UTC, acalma commented on skactiveml/pool/regression/_expected_model_change.py
> +    feature_map: callable
`defaults to identity function`?

2022-06-02 15:02 UTC, acalma commented on skactiveml/base.py
> +    Bass class for scikit-activeml regressors.
typo?

```suggestion
    Base class for scikit-activeml regressors.
```

2022-06-02 15:18 UTC, acalma commented on skactiveml/base.py
> +        return result
I do not think that this is a good design pattern: A function that sometimes return 1, 2 or 3 values.

I would suggest always returning `std` and `entropy` . Then the other dev calling this function can use `_` to ignore the params they do not want.

2022-06-02 15:19 UTC, acalma commented on skactiveml/base.py
> +        return result
see also https://stackoverflow.com/questions/44044932/how-can-a-function-optionally-return-one-or-more-values

2022-06-02 15:24 UTC, acalma commented on skactiveml/base.py
> +        """Returns random variate samples from the predicted target distribution
@mherde @dakot `random variate samples` 
This is new to me. I assume that you mean `random samples`. If not, pls explain it to me shortly or a link to a "random variate sample"

2022-06-02 15:25 UTC, acalma commented on skactiveml/regressor/_wrapper.py
> +            Number of random variate samples to be drawn.
see above `random variate sample` comment

2022-06-02 15:36 UTC, acalma commented on skactiveml/pool/regression/_expected_model_change.py
> +    missing_label : scalar or string or np.nan or None, default=np.nan
if you change the default value for missing label in `skactiveml.utils` then you will have to change the documentation all over the place, as it won't be np.nan. 

I would suggest something like:

```suggestion
    missing_label : scalar or string or np.nan or None, default=skactiveml.utils.MISSING_LABEL
```

2022-06-02 15:39 UTC, acalma commented on skactiveml/pool/regression/_expected_model_output_change.py
> +    missing_label : scalar or string or np.nan or None, default=np.nan
see missing label comment above

2022-06-02 15:44 UTC, acalma commented
@dakot have you thought about adding `pylint` https://www.henryschmale.org/2021/01/21/pylint-github-actions.html or `Flake8` ?

It looks like a lot of changes were just formatting updates or replacing single quotes with double quotes.

I think that adding some basic linting will reduce the effort for maintaining and reviewing the code.

2022-06-07 16:21 UTC, acalma commented on skactiveml/pool/regression/_expected_model_variance.py
> +    missing_label : scalar or string or np.nan or None, default=np.nan
see missing value comment above

2022-06-07 16:27 UTC, acalma commented on skactiveml/pool/regression/_greedy_sampling.py
> +    missing_label : scalar or string or np.nan or None, default=np.nan
I will not comment every one of them. Please see my comment above and , eventually, update all docs.

2022-06-07 16:50 UTC, acalma commented on skactiveml/pool/regression/_greedy_sampling.py
> +            utilities = utilities[:, len(X) :]
minor change, just deleted the space in front of ':'

```suggestion
            utilities = utilities[:, len(X):]
```

2022-06-07 17:01 UTC, acalma commented on skactiveml/pool/regression/_information_gain_maximization.py
> +            The expected information gain for each candidate sample.
return value name `query_indices` and the description do not seem to match. Am I missing something?

2022-06-07 17:05 UTC, acalma commented on skactiveml/pool/regression/_information_gain_maximization.py
> +        """
copy paste error?

I assume it returns the KL divergence, isn't it?

2022-06-07 17:10 UTC, acalma commented on skactiveml/pool/regression/_information_gain_maximization.py
> +def cross_entropy(
I wouldn't expect to import the `cross_entropy` from `pool.regression._information_gain_maximization` . Maybe you can find a more suitable location for this function?

2022-06-07 17:15 UTC, acalma commented on skactiveml/pool/regression/_query_by_committee.py
> +            `sample_weight`.
I assume that the description is not correct or I do not understand why we are talking about a `classifier`

2022-06-07 17:16 UTC, acalma commented on skactiveml/pool/regression/_query_by_committee.py
> +            Regressor to predict the data.
is it one or more regressors? may add more docu?

2022-06-07 17:27 UTC, acalma commented on skactiveml/pool/regression/_query_by_committee.py
> +                    est_arr[idx] = est.fit(X, y, sample_weight)
`k_bootstraps` does not affect the ensemble here. Maybe update the documentation for `k_bootstraps` and what it influences?

2022-06-10 14:54 UTC, mherde requested changes

2022-06-10 14:54 UTC, mherde commented on skactiveml/pool/regression/utils/_model_fitting.py
> +def update_reg(
Move as private _update_reg to `skactiveml.utils._regression.py`

2022-06-10 14:54 UTC, mherde commented on skactiveml/pool/regression/utils/_model_fitting.py
> +def update_X_y(X, y, y_update, idx_update=None, X_update=None):
Move as private _update_X_y to skactiveml.utils._regression.py

2022-06-10 14:54 UTC, mherde commented on skactiveml/pool/regression/_query_by_committee.py
> +class QueryByCommittee(SingleAnnotatorPoolQueryStrategy):
Move to pool._query_by_committee with name QueryByCommitteeRegression

2022-06-10 14:54 UTC, mherde commented on skactiveml/pool/regression/_query_by_committee.py
> +            est_arr = bootstrap_estimators(
rethink whether we keep this third option

2022-06-10 14:54 UTC, mherde commented on skactiveml/regressor/_nadaraya_watson_regressor.py
> +    """NadarayaWatsonRegressor
use this parameters as default for NIC... and say in documentation this correspnds to Nadarya

2022-06-10 14:54 UTC, mherde commented on skactiveml/regressor/_wrapper.py
> +class SklearnRegressor(SkactivemlRegressor, MetaEstimatorMixin):
What about the `partial_fit`?

2022-06-10 14:54 UTC, mherde commented on skactiveml/regressor/_wrapper.py
> +class SklearnRegressor(SkactivemlRegressor, MetaEstimatorMixin):
See classifier wrapper for comparison

2022-06-10 14:54 UTC, mherde commented on skactiveml/regressor/_wrapper.py
> +            The distribution of the targets at the test samples.
Add that norm distribution is assumed.

2022-06-10 14:54 UTC, mherde commented on skactiveml/regressor/_wrapper.py
> +class SklearnProbabilisticRegressor(ProbabilisticRegressor, SklearnRegressor):
SklearnNormalRegressor (since normal distribution is assumed)

2022-06-10 14:54 UTC, mherde commented on skactiveml/utils/_selection.py
> +def combine_ranking(*iter_ranking, rank_method=None, rank_per_batch=False):
Maybe move to representativeness and diversirty? Or do you think that this method will be used by others, e.g., for strategy combination?

2022-06-10 14:54 UTC, mherde commented on skactiveml/visualization/__init__.py
> +from ._data_set import gaussian_noise_generator_1d, sample_generator_1d
Do we need these functions or could we use make_blobs for examples?

2022-06-10 14:54 UTC, mherde commented on skactiveml/visualization/_data_set.py
> +import numpy as np
maybe those functions are too specific and can be directly implemented within the notebook

2022-06-24 11:50 UTC, mherde requested changes

2022-08-19 09:34 UTC, mherde requested changes

2022-08-19 09:34 UTC, mherde commented on skactiveml/stream/tests/test_uncertainty_zliobaite.py
>          return Split
**_Caution: Too long_**. Black must be with 79 characters.

2022-08-19 09:34 UTC, mherde commented on skactiveml/utils/_selection.py
> +def combine_ranking(*iter_ranking, rank_method=None, rank_per_batch=False):
Please comment @LukasLuehrs

2022-08-19 09:34 UTC, mherde commented on skactiveml/utils/_validation.py
> +    if n_free_parameters is None:
For None, it is better to allow not testing the number of free parameters.

2022-08-19 09:34 UTC, mherde commented on skactiveml/utils/_validation.py
> +            f"The number of free parameters of the callable has to "
```suggestion
            f"The number of free parameters of the callable {name} has to "
```

2022-08-19 09:34 UTC, mherde commented on skactiveml/utils/_validation.py
> +def check_callable(func, name, n_free_parameters=None):
Define as private function for upcoming release.

2022-08-19 09:34 UTC, mherde commented on skactiveml/utils/_validation.py
> +    n_free_params = len(
```suggestion
    n_actual_free_parameters = len(
```
What is the meaning of free parameters? Do you just mean the mandatory parameters without default values? Then maybe use `n_mandatory_parameters` and `n_actual_mandatory_parameters`.

2022-08-19 09:34 UTC, mherde commented on skactiveml/visualization/_data_sets.py
> +    n_samples, *intervals, interval_density=1, random_state=None
```suggestion
    n_samples, intervals, interval_density=1, random_state=None
```
Define intervals directly as list similar to centers in sklearn.data_sets.make_blobs.

2022-08-19 09:34 UTC, mherde commented on skactiveml/visualization/_data_sets.py
> +    X, *intervals, interval_std=1, default_std=0.5, random_state=None
```suggestion
    X, intervals, interval_std=1, default_std=0.5, random_state=None
```
Define intervals directly as list similar to centers in sklearn.data_sets.make_blobs.

2022-08-19 09:34 UTC, mherde commented on skactiveml/visualization/_data_sets.py
> +import numpy as np
We need discuss whether this file is necessary. `make_blobs` can also be used to generate such data sets.

2022-08-19 09:34 UTC, mherde commented on skactiveml/visualization/_misc.py
> +
Move to datasets file.

2022-09-13 11:12 UTC, merged