Stream docs
scikit-activeml/scikit-activeml pull request #286
Opened 2023-03-28 10:30 UTC by AlexanderBenz

2023-03-31 07:56 UTC, tpham93 requested changes

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/stream/_density_uncertainty.json
> +    "refs" : ["settles2009active"],
Fix reference: https://proceedings.mlr.press/v36/ienco14.html

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/stream/_density_uncertainty.json
> +    "refs" : ["settles2009active"],
Fixe Reference for all CogDQS strategies: https://ieeexplore.ieee.org/document/9492291/

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/stream/_stream_baselines.json
> +    "refs" : ["settles2009active"],
Remove reference

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/stream/_stream_baselines.json
> +    "refs" : ["settles2009active"],
Remove reference

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/stream/_stream_probabilistic_al.json
> +    "refs" : ["settles2009active"],
https://link.springer.com/chapter/10.1007/978-3-319-24465-5_13

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/stream/_uncertainty_sampling.json
Fix references: https://ieeexplore.ieee.org/document/6414645

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/template_stream.py
> +# mesh_instances = np.array([X_mesh.reshape(-1), Y_mesh.reshape(-1)]).T
cleanup

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/template_stream.py
> +    X_train_array = np.array(X_train).reshape([-1, 1])
X_labeled and X_train_array (74-77) not used anywhere

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/template_stream.py
> +    # colors.append("r" if y_cand == classes[0] else "b")
cleanup

2023-03-31 07:56 UTC, tpham93 commented on docs/examples/template_stream.py
> +            + f"budget is {budget_list[-1]:.4f}"
Replace by queried_count/(tx+1) and remove budget_list

2023-03-31 07:56 UTC, tpham93 commented on skactiveml/stream/_density_uncertainty.py
> +        utilities = 1 - utilities[0]
rename in confidence

2023-03-31 07:56 UTC, tpham93 commented on skactiveml/stream/_density_uncertainty.py
> +        utilities = 1 - utilities
rename in confidence

2023-03-31 07:56 UTC, tpham93 commented on skactiveml/stream/_uncertainty_zliobaite.py
> +        utilities = 1 - utilities
rename in confidence

2023-03-31 07:56 UTC, tpham93 commented on skactiveml/visualization/tests/test_feature_space.py
Add tests where pdf files are compared so look of plots is consistent. See pool tests where compare_images is used

2023-04-11 13:52 UTC, tpham93 reviewed
Looks good now.

2023-04-11 13:52 UTC, tpham93 commented on docs/examples/template_stream.py
> +    # check whether to sample the instance or not
Capitalisation

2023-04-18 11:21 UTC, mherde requested changes

2023-04-18 11:21 UTC, mherde commented on docs/examples/template_stream.py
> +    n_features=2,
```suggestion
    n_features=1,
```

2023-04-18 11:21 UTC, mherde commented on docs/examples/template_stream.py
> +X_init = X[:init_size, :]
```suggestion
X_init = X[:init_size]
```

2023-04-18 11:21 UTC, mherde commented on docs/examples/template_stream.py
> +X_stream = X[init_size:, :]
```suggestion
X_stream = X[init_size:]
```

2023-04-18 11:21 UTC, mherde commented on docs/examples/template_stream.py
> +            + f"budget is {queried_count / (t_x + 1):.4f}"
```suggestion
            + f"budget is {sum(queried_indices) / (t_x + 1):.4f}"
```

2023-04-18 11:21 UTC, mherde commented on docs/examples/template_stream.py
> +    queried_count += len(sampled_indices)
```suggestion
```

2023-04-18 11:21 UTC, mherde commented on skactiveml/stream/_density_uncertainty.py
> +        utilities = 1 - confidence[0]
Check indexing.

2023-04-18 11:21 UTC, mherde commented on skactiveml/visualization/_feature_space.py
> +    X : array-like of shape (n_samples, n_features)
```suggestion
    X : array-like of shape (n_samples, 1)
```

2023-04-18 11:21 UTC, mherde commented on skactiveml/visualization/_feature_space.py
> +        Indicates which instances from candidates have been queried.
```suggestion
        Indicates which instances from candidates have been queried.
    classes : ...
```

2023-04-18 11:21 UTC, mherde commented on skactiveml/visualization/_feature_space.py
> +    check_array(X, ensure_2d=False)
check shape of `X` to be `(n_samples, 1)`

2023-04-18 11:21 UTC, mherde commented on skactiveml/visualization/_feature_space.py
> +    X : array-like of shape (n_samples, n_features)
```suggestion
    X : array-like of shape (n_samples,)
```

2023-04-18 11:21 UTC, mherde commented on skactiveml/visualization/_feature_space.py
> +    Returns
```suggestion

    Returns
```

2023-04-18 11:21 UTC, mherde commented on skactiveml/visualization/_feature_space.py
> +    check_array(pred_list, ensure_2d=False, ensure_min_samples=0)
Check whether it needs to be a column array, then use `check_column` instead.

2023-04-20 09:19 UTC, tpham93 approved these changes

2023-04-20 09:26 UTC, mherde approved these changes

2023-04-20 09:28 UTC, merged