Restructure stream and budget manager tests
scikit-activeml/scikit-activeml pull request #348
Opened 2023-11-01 14:26 UTC by AlexanderBenz

See #303

**Additional context**
Includes test for stream and budget manager

2023-11-06 14:00 UTC, mherde requested changes

2023-11-22 14:19 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +    ):
Done

2023-11-22 14:19 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +    def test_query_param_clf(self, test_cases=None):
Done

2023-11-22 14:19 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +            for exclude_clf, exclude_reg, query_params in [
Done

2023-11-22 14:23 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +                    ("", ["A", "B"], str, None),
Done

2023-11-22 14:23 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +            (False, True, self.query_default_params_clf),
Done

2023-11-22 14:24 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +            if query_params is not None:
Done

2023-11-22 14:24 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +                # (True, False, self.query_default_params_reg),
Done

2023-11-22 14:24 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +        expected_output=None,
Done

2023-11-22 14:24 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +        expected_utilities=None,
Done

2023-11-22 14:24 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +        candidat = np.array([[0.5, 0.5]])
Done

2023-11-27 10:21 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +            if "clf" in query_params and i > 0:
Done

2023-11-27 10:21 UTC, AlexanderBenz commented on skactiveml/tests/template_query_strategy.py
> +        test_cases += [(Dummy, TypeError), ([[]], None)]
Done

2023-11-27 15:50 UTC, mherde requested changes

2023-12-04 14:47 UTC, mherde requested changes

2023-12-04 14:47 UTC, mherde commented on skactiveml/tests/template_query_strategy.py
> +        budget_manager_param_dict=None,
```suggestion
        budget_manager_param_dict=None,
        X=None,
        y=None,
        candidate=None,
        queried_indices=None
```
Add these parameters as optional ones. If they are set to `None`, we use your current setup as default. As a default case, generating the candidate with a fixed random state would also be better to have better variability.

2023-12-04 14:47 UTC, mherde commented on skactiveml/tests/template_query_strategy.py
> +                # self.assertEqual(qs_output2, qs_output)
```suggestion

```

2023-12-04 14:47 UTC, mherde commented on skactiveml/tests/template_query_strategy.py
> +                # self.assertEqual(expected_output, qs_output)
```suggestion
```

2023-12-04 14:47 UTC, mherde commented on skactiveml/tests/template_query_strategy.py
> +        budget_manager_param_dict=None,
Add comments to have a better overview of this long method.

2023-12-04 14:47 UTC, mherde commented on skactiveml/tests/template_query_strategy.py
> +            utilities2 = []
```suggestion
```

2023-12-04 14:47 UTC, mherde commented on skactiveml/tests/template_query_strategy.py
> +            qs_output2 = []
```suggestion
```

2023-12-18 17:00 UTC, mherde approved these changes

2023-12-18 17:00 UTC, mherde commented on skactiveml/tests/template_budget_manager.py
> +        candidat = np.array([0.3])
```suggestion
        candidate = np.array([0.3])
```

2023-12-18 17:00 UTC, mherde commented on skactiveml/tests/template_budget_manager.py
> +        expected_output=None,
```suggestion
        expected_output,
```

2024-01-08 14:10 UTC, merged