Restructure estimator tests
scikit-activeml/scikit-activeml pull request #356
Opened 2023-11-24 12:30 UTC by AlexanderBenz

See #303 

**Additional context**
Include tests for classifier and regression

2023-11-24 12:46 UTC, AlexanderBenz commented on skactiveml/tests/template_estimator.py
> +        # test_cases = [([1.0, "nan", 0.9], None)]
@mherde

2023-11-24 12:47 UTC, AlexanderBenz commented on skactiveml/regressor/tests/test_nic_kernel_regressor.py
> +        # TODO: Test is missing
@mherde

2023-12-04 17:01 UTC, tpham93 requested changes

2023-12-06 14:40 UTC, tpham93 requested changes

2023-12-06 14:40 UTC, tpham93 commented on skactiveml/tests/template_estimator.py
> +        if hasattr(self.estimator_class, "predict_freq"):
```suggestion
```

2024-01-08 16:15 UTC, mherde requested changes

2024-01-08 16:15 UTC, mherde commented on skactiveml/regressor/tests/test_nic_kernel_regressor.py
> +        self.estimator_class_string = "NICKernelRegressor"
What is the purpose of this string?

2024-01-08 16:15 UTC, mherde commented on skactiveml/regressor/tests/test_nic_kernel_regressor.py
> +        self.estimator_class_string = "NadarayaWatsonRegressor"
Do we need this string?

2024-01-08 16:15 UTC, mherde commented on skactiveml/regressor/tests/test_wrapper.py
> +    def test_fit(self):
Whats is the purpose of this test?

2024-01-16 16:01 UTC, tpham93 commented on skactiveml/classifier/tests/test_wrapper.py
> +        }
@AlexanderBenz Can you have a look at this? We don't understand why we need to override the init parameters for test_fit_param_X

2024-01-16 16:16 UTC, tpham93 commented on skactiveml/tests/template_estimator.py
> +        test_cases += [(X, None), ("Test", ValueError)]
@AlexanderBenz can you check this again?

2024-01-16 16:18 UTC, mherde requested changes

2024-01-16 16:18 UTC, mherde commented on skactiveml/tests/template_estimator.py
>                      init_params[key] = val
@AlexanderBenz 
You can use here also the update function of the dictionary.

2024-01-17 15:02 UTC, tpham93 approved these changes

2024-01-23 11:21 UTC, mherde approved these changes

2024-01-23 11:22 UTC, merged