359 Regression tree-based AL
scikit-activeml/scikit-activeml pull request #371
Opened 2024-01-09 12:53 UTC by Pascal112

Closes #ISSUE_NUMBER

2024-03-07 14:33 UTC, mherde requested changes
Further discussion will follow in the next meeting.

2024-03-12 16:30 UTC, mherde requested changes

2024-03-12 16:30 UTC, mherde commented on skactiveml/pool/tests/test_regression_tree_based_al.py
> +        np.testing.assert_array_equal(np.nansum(utilities[0]), batch_size)
```suggestion
```
Test is redundant due to the subsequent line of code.

2024-03-12 16:30 UTC, mherde commented on skactiveml/pool/tests/test_regression_tree_based_al.py
> +        DELTA = np.array([1, 1, 1])
```suggestion
        delta = np.array([1, 1, 1])
```

2024-03-12 16:30 UTC, mherde commented on docs/examples/pool/_regression_tree_based_al.json
> +    "title" : "Regression Tree Based Active Learning (RT-AL) with representativity Selection",
```suggestion
    "title" : "Regression Tree Based Active Learning (RT-AL) with Representativity Selection",
```

2024-04-09 11:19 UTC, mherde approved these changes

2024-04-15 12:34 UTC, AshnaJose commented on docs/examples/template_pool_regression_batch.py
> +# Initialise the classifier.
regressor

2024-04-15 14:13 UTC, mherde requested changes

2024-04-15 14:13 UTC, mherde commented on skactiveml/pool/_regression_tree_based_al.py
> +
Can we use the `simple_batch ` at the end for representativity?

2024-07-18 17:21 UTC, mherde approved these changes

2024-07-18 17:22 UTC, merged