Add Evaluation of Pool Query Strategies
scikit-activeml/scikit-activeml pull request #376
Opened 2024-01-24 15:37 UTC by Cheng-JY

1. Add a Evaluation notebook of 6 poolbased query Strategies:

- Random Sampling
- Uncertainty Sampling
- Discriminative AL
- Core Set
- TypiClust
- Badge

2. This Evaluation based on pre-processing dataset ```Flowers102``` with ```Dinov2```

3. The Evaluation results is illustrated with a learning curves

Side Consideration:
I have changed the query_batch_size from 32 to 8, so that the learning curve looks better and it does not immediately reach its upper bound.

2024-02-13 16:49 UTC, tpham93 requested changes

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "Apply necessary transformations to the datasets, including resizing images to a standardised format. This ensures consistency of input dimensions to the DINOv2 model."
```suggestion
    "Apply necessary transformations to the datasets, including resizing images to a standardized format. This ensures consistency of input dimensions with the DINOv2 model."
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "batch_size = 4"
```suggestion
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "def load_and_process_dataset(dataset_name, root_dir, is_train):\n",
```suggestion
    "def load_and_process_dataset(root_dir, is_train, batch_size=4):\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "dinov2_vitb14.to(device)"
```suggestion
    "hub.set_dir('cache/')\n",
    "dinov2_vitb14 = torch.hub.load(\"facebookresearch/dinov2\", \"dinov2_vitb14\")\n",
    "\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "\n",
    "dinov2_vitb14.to(device)"
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "Firstly, we begin by loading the CIFAR-10, CIFAR-100, and Flowers-102 datasets.\n",
```suggestion
    "Firstly, we begin by loading the Flowers-102 dataset.\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "After that, we employ the pre-trained DINOv2 model to generate embeddings for each image in the datasets and save them in a npy file."
```suggestion
    "After that, we employ the pre-trained DINOv2 model to generate embeddings for each image in the dataset and save them in a npy file."
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "    - is_train (bool): Boolean indicating whether the dataset is for training (True) or validation (False).\n",
```suggestion
    "    Parameters:\n",
    "    - root_dir (str): Root directory where the dataset will be stored.\n",
    "    - is_train (bool): Boolean indicating whether the dataset is for training (True) or validation (False).\n",
    "    - batch_size (int): The batch_size used for the DataLoader.\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "    dataset = datasets.__dict__[dataset_name](root=root_dir, split=split, download=True, transform=transforms)\n",
```suggestion
    "    dataset = datasets.Flowers102(root=root_dir, split=split, download=True, transform=transforms)\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "    # Create a DataLoader\n",
```suggestion
    "    # Create DataLoader\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "    # Load the dataset\n",
```suggestion
    "    # Load dataset\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +  },
Add a cell that defines a variable named 'data_dir' that points to "./data"

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "np.save('./embedding_data/flowers102_dinov2B_y_test.npy', flowers102_y_test_true)"
export to data_dir as well

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "y_test_true = np.load('./embedding_data/flowers102_dinov2B_y_test.npy')\n",
Use data_dir

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "The embeddings we have computed can be used as an input in a classification model. For this guide, we will be using LogisticRegression from ```sklearn``` [5]. Moreover, we handle the creation of
```suggestion
    "The embeddings we have computed can be used as an input to a classification model. For this guide, we use `LogisticRegression` from `scikit-klearn`. Moreover, we handle the creation of query strategies using factory functions to simplify the seperation of classifiers and query strategies across repetitions and folds.\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "[5] ‘sklearn.linear_model.LogisticRegression’, scikit-learn. Accessed: Jan. 24, 2024. [Online]. Available: https://scikit-learn/stable/modules/generated/sklearn.linear_model.LogisticRegression.h
```suggestion
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "clf = SklearnClassifier(LogisticRegression(), classes=np.arange(dataset_classes), random_state=gen_seed(master_random_state))\n",
Add a line break to shorten this line

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "For this experiment, we need to define how the strategies should be compared against one another. Here the number of repetitions (```n_reps```), the numer of queries (```n_cycles```), the size o
```suggestion
    "For this experiment, we need to define how the strategies should be compared against one another. Here the number of repetitions (```n_reps```), the number of cycles(```n_cycles```), and the size of each query (```query_batch_size```) need to be defined. "
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "n_reps = 1\n",
```suggestion
    "n_reps = 3\n",
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "The actual experiment loops all over the query strategies. The average accuracy over the test set is recorded for each cycle and stored in the ```results``` dictionary."
```suggestion
    "The actual experiment loops over all query strategies. The accuracy for the test set is stored for each cycle and repetition in the `results` dictionary."
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "We use learning curves to compare strategies. We visualise the average accuracy, averaged over all repetitions and folds, relative to the number of queries. In addition, the legend provides insi
```suggestion
    "We use learning curves to compare strategies. We visualize the average accuracy over all repetitions. In addition, the legend provides insight into the area under the learning curve, which indicates the average accuracy over all cycles."
```

2024-02-13 16:49 UTC, tpham93 commented on tutorials/05_pool_evaluation_with_self_supervised.ipynb
> +    "plt.title(\"LogisticRegression\")\n",
```suggestion
    "plt.title(f\"LogisticRegression with query batch size {query_batch_size}\")\n",
```

2024-02-20 12:04 UTC, tpham93 commented on tutorials/05_pool_al_with_self_supervised_learning.ipynb
> +    "For this experiment, we need to define how the strategies should be compared against one another. Here the number of repetitions (```n_reps```), the numer of queries (```n_cycles```), the size o
```suggestion
    "For this experiment, we need to define how the strategies should be compared against one another. Here the number of repetitions (```n_reps```), the number of cycles(```n_cycles```), and the size of each query (```query_batch_size```) need to be defined. "
```

2024-02-20 12:04 UTC, tpham93 commented on tutorials/05_pool_al_with_self_supervised_learning.ipynb
> +    "The actual experiment loops all query strategies. The accuracy for the test set is stored for each cycle and repetition in the `results` dictionary."
```suggestion
    "The actual experiment loops over all query strategies. The accuracy for the test set is stored for each cycle and repetition in the `results` dictionary."
```

2024-02-20 12:04 UTC, tpham93 commented on tutorials/05_pool_al_with_self_supervised_learning.ipynb
> +    "We use learning curves to compare strategies. We visualize the average accuracyover all repetitions. In addition, the legend provides insight into the area under the learning curve, which indica
```suggestion
    "We use learning curves to compare strategies. We visualize the average accuracy over all repetitions. In addition, the legend provides insight into the area under the learning curve, which indicates the average accuracy over all cycles."
```

2024-02-21 09:38 UTC, mherde approved these changes

2024-02-21 09:39 UTC, merged