Check random state
scikit-activeml/scikit-activeml pull request #58
Opened 2020-11-16 16:51 UTC by christoph14

Implement #50

2020-11-16 17:22 UTC, mherde requested changes

2020-11-16 17:22 UTC, mherde commented on skactiveml/pool/tests/test_random.py
> +        self.assertRaises(ValueError, rand.query, self.X_cand)
Why do we get an a `ValueError` and not a `TypeError`?

2020-11-16 17:22 UTC, mherde commented on skactiveml/utils/_validation.py
> +from numpy.random.mtrand import RandomState
Use `np.random.RandomState` instead of an additional import.

2020-11-16 17:22 UTC, mherde commented on skactiveml/pool/tests/test_random.py
> +        self.assertRaises(ValueError, rand.query, self.X_cand)
Because `check_random_state` of sklearn raises only `ValueError`.

2020-11-16 17:22 UTC, mherde commented on skactiveml/utils/tests/test_validation.py
> +        self.assertEqual(new_seed, seed * multiplier)
Checks for invalid parameters are missing.

2020-11-23 14:27 UTC, dakot requested changes

2020-11-23 14:27 UTC, dakot commented on skactiveml/pool/_expected_error.py
> +        self.random_state = check_random_state(self.random_state)
`random_state` should be a local variable here (at least other than `self.random_state`)

See also other methods

2020-11-23 14:27 UTC, dakot commented on skactiveml/pool/_expected_error.py
> +        self.random_state = check_random_state(self.random_state)
#50

2020-12-03 08:40 UTC, dakot approved these changes

2020-12-03 08:40 UTC, merged